### ISSUE TITLE
Qodana가 제대로 설정 파일을 참조할 수 없는 문제를 수정한다

### ISSUE THREAD

**Issue by thornscript** [GU-99/grow-up-pms#27]
### 🐞 설명

소스 브랜치의 프로젝트 루트 경로에 `qodana.yaml` 파일이 존재함에도 불구하고 해당 파일을 찾지 못해서 잡이 실패합니다.

### 📄 버그 로그

```shell
Keep running Project configuration ... so far 1m
Detected 0 package.json files under the project to install dependencies
The Project configuration stage completed in 1m 18s
Initializing project…Inspecting with the 'qodana.recommended' profile
Preparing for the Project configuration stage ...
The Project configuration stage completed in 5ms
2024-06-19 07:11:02,730 [  95342] SEVERE - #o.j.q.s.i.r.QodanaInspectionApplication - /data/project/qodana.yaml
java.nio.file.NoSuchFileException: /data/project/qodana.yaml
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at kotlin.io.path.PathsKt__PathReadWriteKt.readText(PathReadWrite.kt:155)
	at kotlin.io.path.PathsKt__PathReadWriteKt.readText$default(PathReadWrite.kt:154)
	at org.jetbrains.qodana.staticAnalysis.inspections.config.QodanaYamlComponent$Companion$load$text$1.invoke(QodanaYamlComponent.kt:69)
	at org.jetbrains.qodana.staticAnalysis.inspections.config.QodanaYamlComponent$Companion$load$text$1.invoke(QodanaYamlComponent.kt:69)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:52)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-06-19 07:11:02,733 [  95345] SEVERE - #o.j.q.s.i.r.QodanaInspectionApplication - Qodana for JVM 2024.1  Build #QDJVM-241.17569.155
2024-06-19 07:11:02,733 [  95345] SEVERE - #o.j.q.s.i.r.QodanaInspectionApplication - JDK: 17.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-06-19 07:11:02,733 [  95345] SEVERE - #o.j.q.s.i.r.QodanaInspectionApplication - OS: Linux
2024-06-19 07:11:02,736 [  95348] SEVERE - #o.j.q.s.i.r.QodanaInspectionApplication - Last Action: 
java.nio.file.NoSuchFileException: /data/project/qodana.yaml
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at kotlin.io.path.PathsKt__PathReadWriteKt.readText(PathReadWrite.kt:155)
	at kotlin.io.path.PathsKt__PathReadWriteKt.readText$default(PathReadWrite.kt:154)
	at org.jetbrains.qodana.staticAnalysis.inspections.config.QodanaYamlComponent$Companion$load$text$1.invoke(QodanaYamlComponent.kt:69)
	at org.jetbrains.qodana.staticAnalysis.inspections.config.QodanaYamlComponent$Companion$load$text$1.invoke(QodanaYamlComponent.kt:69)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:52)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

### 🌏 버그 발생 환경

Ubuntu 22.04(20240609.1.0), Github Actions

### 📚 참고 자료

- [Qodana fails in GitHub on pull request with file not found](https://youtrack.jetbrains.com/issue/QD-9039/Qodana-fails-in-GitHub-on-pull-request-with-file-not-found)

### ⏰ 추정 시간

1시간

### ⏰ 소요 시간

1시간

**Comment by thornscript** [comment]
> 메인 브랜치에 Qodana 설정 파일이 없고, PR의 소스 브랜치에만 Qodana 설정 파일이 포함되어 있어서 문제가 발생한 것 같습니다. 강제로 메인 브랜치에 병합하면 Qodana 액션이 성공적으로 실행됩니다.(I found that the problem is related to having a main branch without Qodana config files and adding the Qodana config files in another branch which is source branch for the PR to be merged to the main branch. When I force the merge to main it will run Qodana action successful.)

우선 이 문제를 해결하기 위해서 병합 후에 문제가 해결되었는지 다시 한 번 확인하겠습니다. [참고](https://youtrack.jetbrains.com/issue/QD-9039/Qodana-fails-in-GitHub-on-pull-request-with-file-not-found)
